### ISSUE TITLE
.pause() cuts off 0.5 sec of the end of the video

### ISSUE THREAD

**Issue by tungfam** [NextLevel/NextLevel#127] opened 2018-05-23 20:07 UTC
While using `NextLevel.shared.pause()` it cuts off 0.5 sec of the end of the video.

How to catch the issue. 1. Download Sample project. 2. Run 3. Open stopwatch on desktop. 4. Start at the same time and finish the stopwatch and camera at the same time. 5. You will notice that the video ended earlier than needed.

A simple workaround is to make 0.5 sec delay after the user taps the "pause" button.

But maybe there is a way to fix it in the library.

Hope it helps! Please let me know if you need more details.

**Comment by piemonte** [comment] 2018-06-07 15:13
just realized this is a duplicate of an existing issue. will track it there.

📎 https://github.com/NextLevel/NextLevel/issues/119

**Closed by piemonte** 2018-06-07 15:13 UTC
Labels: bug
