### ISSUE TITLE
Videos are getting cut short

### ISSUE THREAD

**Issue by bennysghost** [NextLevel/NextLevel#119] opened 2018-01-23 19:26 UTC
I've seen this in our implementation and in the sample app. When we record a single video clip, it seems like the last fraction of a second of the clip gets cut off. You can see this in the project's demo app as well. 

To repro in the demo project, hold the capture button to record a clip and just before letting go of the button, mark the clip with an audio cue. You'll notice during playback, the audio cue is not present.

**Comment by klpl** [comment] 2018-01-31 02:11
This issue seems to be caused by the cinematic / auto stabilization mode.  You could try changing it to standard see if it fixes it.

**Comment by hoskin** [comment] 2018-02-22 23:39
This bug is very evident when trying to record short (vine length) clips.

**Comment by hoskin** [comment] 2018-02-23 00:07
Here's a [quick video](https://www.youtube.com/watch?v=5eiMsbWJ-t8) showing this bug running on my iPhone 7, iOS 11.2.5. I record myself tapping three fingers, but the exported video only catches two full taps. And here is the [very basic view controller](https://gist.github.com/hoskin/0097e9d22fb82657864ed27a9949e189).

**Comment by tungfam** [comment] 2018-06-07 20:57
A simple workaround is to make 0.5 sec delay after the user taps the "pause" button.

**Comment by piemonte** [comment] 2018-06-07 21:38
hey @tungfam thanks much. that's a nice idea, i'd like to get to the root cause, found one issue which i'll push shortly.

**Comment by tungfam** [comment] 2018-07-03 21:47
@piemonte just found out that there is also another issue that is most likely connected to this one too.

Issue: saved video captures ~0.5 seconds **before** user actually presses the button to capture the video.

How to repro:
1. install demo proj
2. open app put a hand in front of the camera
3. make some quick gesture and freeze
4. start capturing video right away
5. you will notice that the part of the gesture is in the video even though you started capturing the video **after** you made the hand frozen:)

I'm quite sure this is connected to the same issue with cut off 0.5 secs in the very end.

And surely the easy fix is: call `NextLevel.shared.record()` 0.5 seconds after user taps the button :)

Please let me know if you can't reproduce the issue, I'll try to explain somehow better or take a video.

Thanks!

**Comment by Antonito** [comment] 2018-08-13 22:00
Hello,

I am trying to make a loop recording with this library and it seems I am facing this issue.
Since I'm working with a loop, the 0.5sec delay trick will not work.

Any progress on this issue / solutions ?

Thanks !

**Comment by tungfam** [comment] 2018-08-14 07:27
@Antonito what do you mean by loop recording? could you please share an example or explain?

**Comment by Antonito** [comment] 2018-08-14 07:54
@tungfam I am referring to this concept https://en.wikipedia.org/wiki/Loop_recording

But first I'm trying to record a movie in several chunks and merge them into a single movie, it works fine for the video but the audio has the problems described above.

I'm using a modified version of the demo project and here's the "critical" code:
https://gist.github.com/Antonito/5a382eac141fed16a1691a63e306f2b6

**Comment by Rotemy** [comment] 2018-10-14 12:36
Any news regarding this issue?

**Comment by piemonte** [comment] 2018-10-14 17:02
i'd like to investigate this at some point but haven't had an opportunity. i'm also going to add a dedicated ".movie" capture mode for single clip recording.

**Comment by piemonte** [comment] 2018-10-14 17:07
thanks for the issue/comments too, much appreciated

**Comment by Rotemy** [comment] 2018-10-14 17:50
Please notice that this is reproducible when using the back camera, not the front. 10x.

**Comment by kylesp1995** [comment] 2018-10-18 08:57
I have some problem when capture on back camera. It happens since iOS 11. Waiting resolve of this problem

**Comment by JesslynJanssen** [comment] 2019-05-28 23:18
I tried implementing the 0.5 delay before recording but it doesn't seem to help. Is anyone using any other solutions?

**Comment by tungfam** [comment] 2019-05-30 06:44
@JesslynJanssen, In the end, I built my own video camera (without using libs). It wasn't that hard as I thought. Give it a try.

**Comment by UlanNurmatov** [comment] 2019-07-01 22:43
@tungfam 
Hi, did you find any solution?

**Comment by tungfam** [comment] 2019-07-02 18:41
@UlanNurmatov yes, I built my own camera. Apparently, it wasn't that hard.

Please note, I don't mean that making a video camera library is easy.

For my specific needs, it was not hard for me.

**Comment by UlanNurmatov** [comment] 2019-07-03 22:27
@tungfam Actually I need just a camera library to record square videos, able to pause recording and get final compressed file.  I'm thinking of hiring a freelancer. How many hours should it take?

**Comment by tungfam** [comment] 2019-07-04 14:47
@UlanNurmatov let's move to email/chat so that we don't flood in this thread. please kindly find my email address in my github profile :)

**Comment by piemonte** [comment] 2019-12-04 06:10
please verify with 0.16.1

**Comment by rbarbish** [comment] 2020-01-03 20:43
Is not fixed in 0.16.1 - very easily reproduced with the three tap test in @hoskin 's video.

**Closed** 2020-01-06 05:29 UTC
Labels: bug

**Comment by AmilaDiman** [comment] 2020-03-10 09:14
> @tungfam I am referring to this concept https://en.wikipedia.org/wiki/Loop_recording
> 
> But first I'm trying to record a movie in several chunks and merge them into a single movie, it works fine for the video but the audio has the problems described above.
> 
> I'm using a modified version of the demo project and here's the "critical" code:
> https://gist.github.com/Antonito/5a382eac141fed16a1691a63e306f2b6


@Antonito the gist isn't accessible
